demo_lightdash_dbt:
  target: dev
  outputs:
    dev:
      type: clickhouse
      host: 192.168.246.39
      port: 9000
      user: default
      password: 'Fkvfns@@2025'
      schema: demo
      threads: 7
